### ISSUE TITLE
你好 一个问题

### ISSUE THREAD

**Issue by jj89757hhb** [Janyave/SlideSwitchView#1]
我发现SlideSwitchView 不支持 UICollectionView 的滚动！ 麻烦楼主去看一下这个问题  您这个版本解决这样的问题没

**Comment by Janyave** [comment]
支持的，我在testCollectionView分支中写了个demo，你可以对照参考下。

**Comment by jj89757hhb** [comment]
哦，我这里用的 slideSwitchView 估计不是你写的吧？代码不一样的   但是我这边能支持上托隐藏头部视图

**Comment by Janyave** [comment]
那就不是我写的了。我没有去隐藏顶部视图的

**Comment by Janyave** [comment]
问题有误
